### ISSUE TITLE
Unable to use on zabbix server 4.0

### ISSUE THREAD

**Issue by angoxx** [Cosium/zabbix_zfs-on-linux#4]
Could you add your 4.0 template so it could work with zabbix server 4.0?

**Comment by AceSlash** [comment]
The template 3.0 should work on a 4.0 installation, I did import it myself on a 4.0 instance, did you have an error message?

**Comment by angoxx** [comment]
No I didn't have any error message..

For more informations:

I'm using zfs 0.7.9 on ubuntu 18.04. So I add the ZoL_without_sudo.conf (the Include= is including the zabbix_agentd.d/ folder). After restart the agent, the zabbix server receive all Linux informations, but nothing on all ZFS graph...

**Comment by danboid** [comment]
I had the same issue with the same setup. In my case, all I had to do was ensure

ServerActive

and

Hostname

Were configured correctly in /etc/zabbix/zabbix_agentd.conf on my ZFS host and restart the agent.

@AceSlash Maybe it'd be a good idea to make this clearer in the README? ZABBIX defaults to being passive only it seems so a lot of people won't enable Active monitoring on their clients.

**Comment by AceSlash** [comment]
@danboid you are right. It's been so long since I used any passive setup (for performance reason) that I didn't think about that.

@angoxx I will update the documentation as soon as I can.

In the meantime, I will expand the explanation from @danboid here. What you should ensure is that in `/etc/zabbix/zabbix_agentd.conf`, you have `ServerActive=` defined as your zabbix endpoint IP or DNS.

If you have a mismatch between your server hostname and the "Host name" configured in the zabbix front-end, I would advise you to change the zabbix hostname to be the exact same and adjust the "Visible name" instead to an arbitrary friendly name.

This will make Zabbix items in active mode work if you don't have a firewall blocking the zabbix actives ports between the monitored server and the zabbix server.

If you have a firewall, you have 2 options:
1. Open the necessary port for zabbix active check (TCP 10051) from your monitored host to your zabbix server
2. Set a zabbix proxy that can receive packets from your monitored server, you can then add it as a passive proxy on the zabbix server

**Comment by angoxx** [comment]
Hi,

Thanks a lot, @danboid @AceSlash it's working really fine!

I've now a few questions:

Is it possible to monitor the pool status?

I have a lot of snapshots and I don't want to monitor them, how can I edit to remove the monitoring of snapshots?

**Comment by AceSlash** [comment]
I'm not sure I follow, the template doesn't monitor the snapshots, it monitors only the dataset of type "filesystem" and "volume", the snapshots are only seen as the values for "usedbysnapshots" and "usedbychildren".

The status of discovered pools is monitored and there are several triggers configured by default, including the pool status which you will find in trigger prototypes:

![zfs_triggers](https://user-images.githubusercontent.com/5392990/62557285-fd7d2680-b876-11e9-8b6b-e5c67fac1212.png)

This will raise an alert when a pool status is no longer `ONLINE` (disk missing, pool absent, etc, any error will be reported this way).

Is this not what you need?
